import { ColorClasses, AccentColor } from "./types";

export const ACCENT_COLOR_CLASSES: Record<AccentColor, ColorClasses> = {
  primary: {
    iconBg: "bg-primary/10",
    iconText: "text-primary",
    border: "border-primary/10",
    bg: "bg-primary/5",
  },
  blue: {
    iconBg: "bg-blue-500/10",
    iconText: "text-blue-500",
    border: "border-blue-500/10",
    bg: "bg-blue-500/5",
  },
  green: {
    iconBg: "bg-green-500/10",
    iconText: "text-green-500",
    border: "border-green-500/10",
    bg: "bg-green-500/5",
  },
  purple: {
    iconBg: "bg-purple-500/10",
    iconText: "text-purple-500",
    border: "border-purple-500/10",
    bg: "bg-purple-500/5",
  },
  orange: {
    iconBg: "bg-orange-500/10",
    iconText: "text-orange-500",
    border: "border-orange-500/10",
    bg: "bg-orange-500/5",
  },
  cyan: {
    iconBg: "bg-cyan-500/10",
    iconText: "text-cyan-500",
    border: "border-cyan-500/10",
    bg: "bg-cyan-500/5",
  },
};

export const FOLDER_DESCRIPTIONS: Record<string, string> = {
  src: "Main source code directory",
  lib: "Utility functions and shared libraries",
  utils: "Helper functions and utilities",
  helpers: "Helper functions and utilities",
  config: "Configuration files and settings",
  scripts: "Build and automation scripts",
  tests: "Unit and integration tests",
  test: "Test files and test utilities",
  __tests__: "Jest test files",
  spec: "Test specifications",
  docs: "Documentation and guides",
  examples: "Example code and demos",
  samples: "Sample implementations",
  app: "Application routes and pages (App Router)",
  pages: "Page components and routes",
  components: "Reusable UI components",
  ui: "UI component library",
  hooks: "Custom React/Vue hooks",
  stores: "State management stores",
  store: "State management (Redux/Vuex)",
  context: "React Context providers",
  contexts: "React Context providers",
  styles: "CSS and styling files",
  assets: "Static assets (images, fonts)",
  public: "Publicly served static files",
  static: "Static files and assets",
  api: "API routes and endpoints",
  routes: "Route definitions",
  controllers: "Request handlers",
  models: "Data models and schemas",
  services: "Business logic services",
  middleware: "Middleware functions",
  database: "Database migrations and seeds",
  db: "Database related files",
  migrations: "Database migration files",
  types: "TypeScript type definitions",
  interfaces: "Interface definitions",
  constants: "Constant values and enums",
  providers: "Service providers",
  plugins: "Plugin implementations",
  modules: "Feature modules",
  features: "Feature-based modules",
  core: "Core functionality",
  common: "Shared/common code",
  shared: "Shared utilities and types",
  build: "Build output directory",
  dist: "Distribution/compiled files",
  out: "Output directory",
  ".github": "GitHub Actions and workflows",
  ".vscode": "VS Code configuration",
  docker: "Docker configuration files",
  deploy: "Deployment configurations",
  infra: "Infrastructure as code",
  terraform: "Terraform configurations",
  k8s: "Kubernetes manifests",
  kubernetes: "Kubernetes configurations",
  packages: "Monorepo packages",
  apps: "Application packages (monorepo)",
  prisma: "Prisma schema and migrations",
  drizzle: "Drizzle ORM configuration",
  supabase: "Supabase configuration",
};

export const TECH_ICONS: Record<string, string> = {
  typescript: "📘",
  javascript: "📒",
  python: "🐍",
  rust: "🦀",
  go: "🐹",
  java: "☕",
  ruby: "💎",
  php: "🐘",
  swift: "🍎",
  kotlin: "🎯",
  "c#": "🔷",
  "c++": "⚡",
  react: "⚛️",
  "next.js": "▲",
  nextjs: "▲",
  vue: "💚",
  "vue.js": "💚",
  angular: "🅰️",
  svelte: "🔶",
  nuxt: "💚",
  "nuxt.js": "💚",
  remix: "💿",
  astro: "🚀",
  "node.js": "💚",
  nodejs: "💚",
  express: "🚂",
  fastify: "⚡",
  nestjs: "🐱",
  django: "🎸",
  flask: "🧪",
  fastapi: "⚡",
  rails: "💎",
  laravel: "🔴",
  spring: "🌱",
  postgresql: "🐘",
  postgres: "🐘",
  mysql: "🐬",
  mongodb: "🍃",
  redis: "🔴",
  sqlite: "📦",
  prisma: "🔷",
  drizzle: "💧",
  supabase: "⚡",
  docker: "🐳",
  kubernetes: "☸️",
  aws: "☁️",
  vercel: "▲",
  netlify: "🔷",
  github: "🐙",
  graphql: "💜",
  rest: "🔗",
  trpc: "🔷",
  tailwindcss: "🎨",
  "tailwind css": "🎨",
  css: "🎨",
  sass: "💅",
  scss: "💅",
  "styled-components": "💅",
  jest: "🃏",
  vitest: "⚡",
  playwright: "🎭",
  cypress: "🌲",
  redux: "💜",
  zustand: "🐻",
  jotai: "👻",
  recoil: "⚛️",
  tensorflow: "🧠",
  pytorch: "🔥",
  openai: "🤖",
  langchain: "🦜",
};